### ISSUE TITLE
Issue running on Hass.io with docker

### ISSUE THREAD

**Issue by Kisty** [Sanderhuisman/docker_monitor#25]
I'm trying to set this up on my old netbook running [Hass.io with docker](https://github.com/home-assistant/hassio-installer). Is it possible to run this with Hass.io? I think it might be, Also, am on x86 architecture. Is that a problem?

**Comment by Kisty** [comment]
I've tried setting it up but I'm getting a stacktrace. Is that to do with no docker socket being mounted from the host?
```
Error during setup of component docker_monitor
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/docker_monitor/__init__.py", line 112, in setup
    api = DockerAPI(host)
  File "/config/custom_components/docker_monitor/__init__.py", line 175, in __init__
    for container in self._client.containers.list(all=True) or []:
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 918, in list
    since=since)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 208, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 225, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```
Running master (0.0.4) because I couldn't get 0.1.2 working.

Config: 
```
docker_monitor:
  containers:
    - awesome_villani
  monitored_conditions:
    - utilization_version
    - container_status
    - container_memory_usage
    - container_memory_percentage_usage
    - container_cpu_percentage_usage
```

**Comment by Sanderhuisman** [comment]
@Kisty It looks like the component cannot connect to the Docker socket (simply a file in Linux). You have to mount the Docker socket as volume such that the component can read the information.

**Comment by Kisty** [comment]
@Sanderhuisman thanks for that. And how do I mount the docker socket from within Hass.io? Do I need to modify the `hassio.service` file (or something like that) on my host machine (running ubuntu). I can't see an option for it on Hass.io configuration in home assistant.

**Comment by Kisty** [comment]
There's no mention of `hosts` config on the README.md for `master`. I think you might've been looking at the 0.1.2 version. If you're on the master branch, try `url` instead.

https://github.com/Sanderhuisman/docker_monitor/blob/7b97a0679f05c409a50777a615654da31ce740a1/custom_components/docker_monitor/__init__.py#L109

**Comment by Kisty** [comment]
Looks like Hass.io isn't compatible with sockets. I used TCP API in the end as per [these instructions](https://community.home-assistant.io/t/hass-io-exposing-docker-sock-for-docker-monitor/128013/5).
